### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JaisDK** [Darkhax-Minecraft/BotanyPots#55] opened 2020-07-10 22:57 UTC
https://gist.github.com/JaisDK/568d846fe0f34d2050a720b25f1f0f7f

**Comment by Darkhax** [comment] 2020-07-11 00:48
Duplicate of https://github.com/Darkhax-Minecraft/BotanyPots/issues/54 The fix is to update Bookshelf to 6.0.2

**Closed as completed by Darkhax** 2020-07-11 00:48 UTC
