### ISSUE TITLE
Crashing with JEI

### ISSUE THREAD

**Issue by m4slanka** [Darkhax-Minecraft/BotanyPots#361] opened 2024-01-19 20:53 UTC
Botany pots crashed minecraft 1.20.4 whilst initializing with JEI 
Code -1
![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/157158361/92e3057f-845d-4603-913f-1685990197bc)

link to the gist with the crash report:
https://gist.github.com/m4slanka/ca6808cd9a99d6791e3d3890f40069b9#file-crash-2024-01-19_19-32-43-client

**Comment by Darkhax** [comment] 2024-01-20 02:09
This is a duplicate of #360

**Closed as completed by Darkhax** 2024-01-20 02:09 UTC
