### ISSUE TITLE
Pots deleting non-durability tools (i.e. electric) when right clicked

### ISSUE THREAD

**Issue by Lgmrszd** [Darkhax-Minecraft/BotanyPots#301] opened 2023-01-24 21:09 UTC
After right-clicking Botany Pot with Mining Drill from Industrial Revolution mod, the dirt got converted to Dirt Path (since Drill acts as shovel as well) but the drill itself disappeared from my inventory.  This (obviously) should not happen.

Versions:
Modpack: All Of Fabric 6 (1.3.0)
Botany Pots: 9.0.22
Industrial Revolution: 1.15.1-BETA

**Comment by Darkhax** [comment] 2023-02-01 14:36
Thanks for the report. It looks like this issue is caused by the mining drill having a durability of -1 which is breaking how I handle non-consumable tools. I am looking into the issue and will fix it soon.

**Comment by moshner** [comment] 2023-03-23 17:54
I can confirm this bug happens with the Omni Tool from Tech Reborn as well.

**Comment by Darkhax** [comment] 2023-03-24 11:10
This is fixed in 9.0.29. The issue stems from both mods defining tools with no durability, when this mod tries to damage them it destroys the item instead.

**Closed as completed by Darkhax** 2023-03-24 11:10 UTC
