### ISSUE TITLE
Mystical Agriculture not working

### ISSUE THREAD

**Issue by Magewings** [Darkhax-Minecraft/BotanyPots#231] opened 2022-08-04 19:53 UTC
i dont know if there is a setting to turn on or not but i have try every thing to grow the ma stuff in the botany pots

**Comment by Darkhax** [comment] 2022-08-04 22:02
This can be caused by a number of things. 

1) If you are on 1.18.2 alpha, no modded crops are supported at this time. They will be included at a later point.

2) Make sure you are using the right tier of soil. Mystical Agriculture crops can only grow on the Mystical Agriculture farmland soils.

3) If you are using a modpack made by someone else, they likely removed or modified support for Mystical Agriculture as a balancing measure. If this is the case you will need to ask them how the recipes were disabled.

**Closed as completed by Darkhax** 2022-08-04 22:02 UTC

**Comment by Magewings** [comment] 2022-08-04 22:07
Well I know what my problem is, I’m playing on 1.18.2 so I most likely using alpha. My bad
